/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiCard {
        "clickable"?: boolean;
        "href"?: string;
        "image"?: string;
        "subtitle"?: string;
        "title"?: string;
    }
}
declare global {
    interface HTMLUiCardElement extends Components.UiCard, HTMLStencilElement {
    }
    var HTMLUiCardElement: {
        prototype: HTMLUiCardElement;
        new (): HTMLUiCardElement;
    };
    interface HTMLElementTagNameMap {
        "ui-card": HTMLUiCardElement;
    }
}
declare namespace LocalJSX {
    interface UiCard {
        "clickable"?: boolean;
        "href"?: string;
        "image"?: string;
        "subtitle"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "ui-card": UiCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-card": LocalJSX.UiCard & JSXBase.HTMLAttributes<HTMLUiCardElement>;
        }
    }
}
