/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiPanelModal {
        "open": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLUiPanelModalElement extends Components.UiPanelModal, HTMLStencilElement {
    }
    var HTMLUiPanelModalElement: {
        prototype: HTMLUiPanelModalElement;
        new (): HTMLUiPanelModalElement;
    };
    interface HTMLElementTagNameMap {
        "ui-panel-modal": HTMLUiPanelModalElement;
    }
}
declare namespace LocalJSX {
    interface UiPanelModal {
        "open"?: boolean;
        "title": string;
    }
    interface IntrinsicElements {
        "ui-panel-modal": UiPanelModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-panel-modal": LocalJSX.UiPanelModal & JSXBase.HTMLAttributes<HTMLUiPanelModalElement>;
        }
    }
}
