/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiTable {
        "data": any[];
        "headers": { field: string; label: string }[];
    }
}
declare global {
    interface HTMLUiTableElement extends Components.UiTable, HTMLStencilElement {
    }
    var HTMLUiTableElement: {
        prototype: HTMLUiTableElement;
        new (): HTMLUiTableElement;
    };
    interface HTMLElementTagNameMap {
        "ui-table": HTMLUiTableElement;
    }
}
declare namespace LocalJSX {
    interface UiTable {
        "data"?: any[];
        "headers"?: { field: string; label: string }[];
    }
    interface IntrinsicElements {
        "ui-table": UiTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-table": LocalJSX.UiTable & JSXBase.HTMLAttributes<HTMLUiTableElement>;
        }
    }
}
