/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiTag {
        "color": ColorType;
        "text": string;
    }
}
declare global {
    interface HTMLUiTagElement extends Components.UiTag, HTMLStencilElement {
    }
    var HTMLUiTagElement: {
        prototype: HTMLUiTagElement;
        new (): HTMLUiTagElement;
    };
    interface HTMLElementTagNameMap {
        "ui-tag": HTMLUiTagElement;
    }
}
declare namespace LocalJSX {
    interface UiTag {
        "color"?: ColorType;
        "text"?: string;
    }
    interface IntrinsicElements {
        "ui-tag": UiTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-tag": LocalJSX.UiTag & JSXBase.HTMLAttributes<HTMLUiTagElement>;
        }
    }
}
