/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiSelect {
        "autofocus": boolean;
        "disabled": boolean;
        "form"?: string;
        "multiple": boolean;
        "name"?: string;
        "required": boolean;
        "size"?: number;
    }
}
declare global {
    interface HTMLUiSelectElement extends Components.UiSelect, HTMLStencilElement {
    }
    var HTMLUiSelectElement: {
        prototype: HTMLUiSelectElement;
        new (): HTMLUiSelectElement;
    };
    interface HTMLElementTagNameMap {
        "ui-select": HTMLUiSelectElement;
    }
}
declare namespace LocalJSX {
    interface UiSelect {
        "autofocus"?: boolean;
        "disabled"?: boolean;
        "form"?: string;
        "multiple"?: boolean;
        "name"?: string;
        "required"?: boolean;
        "size"?: number;
    }
    interface IntrinsicElements {
        "ui-select": UiSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-select": LocalJSX.UiSelect & JSXBase.HTMLAttributes<HTMLUiSelectElement>;
        }
    }
}
