/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiSelect {
        "label": string | undefined;
        "options": {
    id: string;
    value: string | number;
    label: string;
  }[];
    }
}
declare global {
    interface HTMLUiSelectElement extends Components.UiSelect, HTMLStencilElement {
    }
    var HTMLUiSelectElement: {
        prototype: HTMLUiSelectElement;
        new (): HTMLUiSelectElement;
    };
    interface HTMLElementTagNameMap {
        "ui-select": HTMLUiSelectElement;
    }
}
declare namespace LocalJSX {
    interface UiSelect {
        "label"?: string | undefined;
        "options"?: {
    id: string;
    value: string | number;
    label: string;
  }[];
    }
    interface IntrinsicElements {
        "ui-select": UiSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-select": LocalJSX.UiSelect & JSXBase.HTMLAttributes<HTMLUiSelectElement>;
        }
    }
}
