'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { UiBadge as UiBadgeElement, defineCustomElement as defineUiBadge } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-badge.js";
import { UiButton as UiButtonElement, defineCustomElement as defineUiButton } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-button.js";
import { UiCard as UiCardElement, defineCustomElement as defineUiCard } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-card.js";
import { UiInput as UiInputElement, defineCustomElement as defineUiInput } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-input.js";
import { UiPanelModal as UiPanelModalElement, defineCustomElement as defineUiPanelModal } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-panel-modal.js";
import { UiSelect as UiSelectElement, defineCustomElement as defineUiSelect } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-select.js";
import { UiTable as UiTableElement, defineCustomElement as defineUiTable } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-table.js";
import { UiTag as UiTagElement, defineCustomElement as defineUiTag } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-tag.js";
import { UiTest as UiTestElement, defineCustomElement as defineUiTest } from "@asllyzuniga/stencil-library/dist-custom-elements/ui-test.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type UiBadgeEvents = NonNullable<unknown>;

export const UiBadge: StencilReactComponent<UiBadgeElement, UiBadgeEvents> = /*@__PURE__*/ createComponent<UiBadgeElement, UiBadgeEvents>({
    tagName: 'ui-badge',
    elementClass: UiBadgeElement,
    react: React,
    events: {} as UiBadgeEvents,
    defineCustomElement: defineUiBadge
});

type UiButtonEvents = NonNullable<unknown>;

export const UiButton: StencilReactComponent<UiButtonElement, UiButtonEvents> = /*@__PURE__*/ createComponent<UiButtonElement, UiButtonEvents>({
    tagName: 'ui-button',
    elementClass: UiButtonElement,
    react: React,
    events: {} as UiButtonEvents,
    defineCustomElement: defineUiButton
});

type UiCardEvents = NonNullable<unknown>;

export const UiCard: StencilReactComponent<UiCardElement, UiCardEvents> = /*@__PURE__*/ createComponent<UiCardElement, UiCardEvents>({
    tagName: 'ui-card',
    elementClass: UiCardElement,
    react: React,
    events: {} as UiCardEvents,
    defineCustomElement: defineUiCard
});

type UiInputEvents = { onInputChange: EventName<CustomEvent<string>> };

export const UiInput: StencilReactComponent<UiInputElement, UiInputEvents> = /*@__PURE__*/ createComponent<UiInputElement, UiInputEvents>({
    tagName: 'ui-input',
    elementClass: UiInputElement,
    react: React,
    events: { onInputChange: 'inputChange' } as UiInputEvents,
    defineCustomElement: defineUiInput
});

type UiPanelModalEvents = NonNullable<unknown>;

export const UiPanelModal: StencilReactComponent<UiPanelModalElement, UiPanelModalEvents> = /*@__PURE__*/ createComponent<UiPanelModalElement, UiPanelModalEvents>({
    tagName: 'ui-panel-modal',
    elementClass: UiPanelModalElement,
    react: React,
    events: {} as UiPanelModalEvents,
    defineCustomElement: defineUiPanelModal
});

type UiSelectEvents = {
    onValueChange: EventName<CustomEvent<{
        name?: string;
        value: string | number;
        option: { id: string; value: string | number; label: string };
    }>>
};

export const UiSelect: StencilReactComponent<UiSelectElement, UiSelectEvents> = /*@__PURE__*/ createComponent<UiSelectElement, UiSelectEvents>({
    tagName: 'ui-select',
    elementClass: UiSelectElement,
    react: React,
    events: { onValueChange: 'valueChange' } as UiSelectEvents,
    defineCustomElement: defineUiSelect
});

type UiTableEvents = NonNullable<unknown>;

export const UiTable: StencilReactComponent<UiTableElement, UiTableEvents> = /*@__PURE__*/ createComponent<UiTableElement, UiTableEvents>({
    tagName: 'ui-table',
    elementClass: UiTableElement,
    react: React,
    events: {} as UiTableEvents,
    defineCustomElement: defineUiTable
});

type UiTagEvents = NonNullable<unknown>;

export const UiTag: StencilReactComponent<UiTagElement, UiTagEvents> = /*@__PURE__*/ createComponent<UiTagElement, UiTagEvents>({
    tagName: 'ui-tag',
    elementClass: UiTagElement,
    react: React,
    events: {} as UiTagEvents,
    defineCustomElement: defineUiTag
});

type UiTestEvents = NonNullable<unknown>;

export const UiTest: StencilReactComponent<UiTestElement, UiTestEvents> = /*@__PURE__*/ createComponent<UiTestElement, UiTestEvents>({
    tagName: 'ui-test',
    elementClass: UiTestElement,
    react: React,
    events: {} as UiTestEvents,
    defineCustomElement: defineUiTest
});
