/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { UiTableHeader, UiTableTemplate } from "./components/ui-table/ui-table";
export { UiTableHeader, UiTableTemplate } from "./components/ui-table/ui-table";
export namespace Components {
    interface UiBadge {
        "color": string;
        /**
          * @default "m"
         */
        "size": string;
        "text"?: string;
    }
    interface UiButton {
        "autofocus"?: boolean;
        "disabled"?: boolean;
        "form"?: string;
        "formaction"?: string;
        "formenctype"?: string;
        "formmethod"?: string;
        "formnovalidate"?: boolean;
        "formtarget"?: string;
        "name"?: string;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'reset' | 'submit';
        "value"?: string;
    }
    interface UiCard {
        /**
          * @default false
         */
        "clickable"?: boolean;
        "href"?: string;
        "image"?: string;
        "subtitle"?: string;
        "title"?: string;
    }
    interface UiInput {
        /**
          * @default false
         */
        "disabled": boolean;
        "hint"?: string;
        "inputId": string;
        "label"?: string;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default "text"
         */
        "type": string;
        "validate": () => Promise<boolean>;
    }
    interface UiPanelModal {
        /**
          * @default true
         */
        "visible": boolean;
    }
    interface UiSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "error": boolean;
        "label"?: string;
        "name"?: string;
        /**
          * @default []
         */
        "options": {
    id: string;
    value: string | number;
    label: string;
  }[];
        "value"?: string | number;
    }
    interface UiTable {
        /**
          * Row data: each object key should match a header field
          * @default []
         */
        "data": any[];
        /**
          * Column definitions: field key and display label
          * @default []
         */
        "headers": UiTableHeader[];
        /**
          * Optional custom cell renderers for columns
         */
        "templates"?: UiTableTemplate;
    }
    interface UiTag {
        /**
          * @default "success"
         */
        "color": ColorType;
        /**
          * @default ""
         */
        "text": string;
    }
    interface UiTest {
        "text": string;
        "textb": string;
    }
}
export interface UiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiInputElement;
}
export interface UiSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiSelectElement;
}
declare global {
    interface HTMLUiBadgeElement extends Components.UiBadge, HTMLStencilElement {
    }
    var HTMLUiBadgeElement: {
        prototype: HTMLUiBadgeElement;
        new (): HTMLUiBadgeElement;
    };
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiCardElement extends Components.UiCard, HTMLStencilElement {
    }
    var HTMLUiCardElement: {
        prototype: HTMLUiCardElement;
        new (): HTMLUiCardElement;
    };
    interface HTMLUiInputElementEventMap {
        "inputChange": string;
    }
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLUiPanelModalElement extends Components.UiPanelModal, HTMLStencilElement {
    }
    var HTMLUiPanelModalElement: {
        prototype: HTMLUiPanelModalElement;
        new (): HTMLUiPanelModalElement;
    };
    interface HTMLUiSelectElementEventMap {
        "valueChange": {
    name?: string;
    value: string | number;
    option: { id: string; value: string | number; label: string };
  };
    }
    interface HTMLUiSelectElement extends Components.UiSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiSelectElementEventMap>(type: K, listener: (this: HTMLUiSelectElement, ev: UiSelectCustomEvent<HTMLUiSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiSelectElementEventMap>(type: K, listener: (this: HTMLUiSelectElement, ev: UiSelectCustomEvent<HTMLUiSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiSelectElement: {
        prototype: HTMLUiSelectElement;
        new (): HTMLUiSelectElement;
    };
    interface HTMLUiTableElement extends Components.UiTable, HTMLStencilElement {
    }
    var HTMLUiTableElement: {
        prototype: HTMLUiTableElement;
        new (): HTMLUiTableElement;
    };
    interface HTMLUiTagElement extends Components.UiTag, HTMLStencilElement {
    }
    var HTMLUiTagElement: {
        prototype: HTMLUiTagElement;
        new (): HTMLUiTagElement;
    };
    interface HTMLUiTestElement extends Components.UiTest, HTMLStencilElement {
    }
    var HTMLUiTestElement: {
        prototype: HTMLUiTestElement;
        new (): HTMLUiTestElement;
    };
    interface HTMLElementTagNameMap {
        "ui-badge": HTMLUiBadgeElement;
        "ui-button": HTMLUiButtonElement;
        "ui-card": HTMLUiCardElement;
        "ui-input": HTMLUiInputElement;
        "ui-panel-modal": HTMLUiPanelModalElement;
        "ui-select": HTMLUiSelectElement;
        "ui-table": HTMLUiTableElement;
        "ui-tag": HTMLUiTagElement;
        "ui-test": HTMLUiTestElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, T> = { [P in K]: T } | { [P in `attr:${K}`]: T } | { [P in `prop:${K}`]: T };

    interface UiBadge {
        "color": string;
        /**
          * @default "m"
         */
        "size"?: string;
        "text"?: string;
    }
    interface UiButton {
        "autofocus"?: boolean;
        "disabled"?: boolean;
        "form"?: string;
        "formaction"?: string;
        "formenctype"?: string;
        "formmethod"?: string;
        "formnovalidate"?: boolean;
        "formtarget"?: string;
        "name"?: string;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'reset' | 'submit';
        "value"?: string;
    }
    interface UiCard {
        /**
          * @default false
         */
        "clickable"?: boolean;
        "href"?: string;
        "image"?: string;
        "subtitle"?: string;
        "title"?: string;
    }
    interface UiInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "hint"?: string;
        "inputId": string;
        "label"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        "onInputChange"?: (event: UiInputCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default "text"
         */
        "type"?: string;
    }
    interface UiPanelModal {
        /**
          * @default true
         */
        "visible"?: boolean;
    }
    interface UiSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "error"?: boolean;
        "label"?: string;
        "name"?: string;
        "onValueChange"?: (event: UiSelectCustomEvent<{
    name?: string;
    value: string | number;
    option: { id: string; value: string | number; label: string };
  }>) => void;
        /**
          * @default []
         */
        "options"?: {
    id: string;
    value: string | number;
    label: string;
  }[];
        "value"?: string | number;
    }
    interface UiTable {
        /**
          * Row data: each object key should match a header field
          * @default []
         */
        "data"?: any[];
        /**
          * Column definitions: field key and display label
          * @default []
         */
        "headers"?: UiTableHeader[];
        /**
          * Optional custom cell renderers for columns
         */
        "templates"?: UiTableTemplate;
    }
    interface UiTag {
        /**
          * @default "success"
         */
        "color"?: ColorType;
        /**
          * @default ""
         */
        "text"?: string;
    }
    interface UiTest {
        "text": string;
        "textb": string;
    }

    interface UiBadgeAttributes {
        "color": string;
        "text": string;
        "size": string;
    }
    interface UiButtonAttributes {
        "autofocus": boolean;
        "disabled": boolean;
        "form": string;
        "formaction": string;
        "formenctype": string;
        "formmethod": string;
        "formnovalidate": boolean;
        "formtarget": string;
        "name": string;
        "type": 'button' | 'reset' | 'submit';
        "value": string;
    }
    interface UiCardAttributes {
        "title": string;
        "subtitle": string;
        "image": string;
        "clickable": boolean;
        "href": string;
    }
    interface UiInputAttributes {
        "label": string;
        "placeholder": string;
        "type": string;
        "inputId": string;
        "hint": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
    }
    interface UiPanelModalAttributes {
        "visible": boolean;
    }
    interface UiSelectAttributes {
        "name": string;
        "label": string;
        "value": string;
        "disabled": boolean;
        "error": boolean;
    }
    interface UiTagAttributes {
        "text": string;
        "color": ColorType;
    }
    interface UiTestAttributes {
        "text": string;
        "textb": string;
    }

    interface IntrinsicElements {
        "ui-badge": Omit<UiBadge, keyof UiBadgeAttributes> & { [K in keyof UiBadge & keyof UiBadgeAttributes]?: UiBadge[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `attr:${K}`]?: UiBadgeAttributes[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `prop:${K}`]?: UiBadge[K] } & OneOf<"color", UiBadge["color"]>;
        "ui-button": Omit<UiButton, keyof UiButtonAttributes> & { [K in keyof UiButton & keyof UiButtonAttributes]?: UiButton[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `attr:${K}`]?: UiButtonAttributes[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `prop:${K}`]?: UiButton[K] };
        "ui-card": Omit<UiCard, keyof UiCardAttributes> & { [K in keyof UiCard & keyof UiCardAttributes]?: UiCard[K] } & { [K in keyof UiCard & keyof UiCardAttributes as `attr:${K}`]?: UiCardAttributes[K] } & { [K in keyof UiCard & keyof UiCardAttributes as `prop:${K}`]?: UiCard[K] };
        "ui-input": Omit<UiInput, keyof UiInputAttributes> & { [K in keyof UiInput & keyof UiInputAttributes]?: UiInput[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `attr:${K}`]?: UiInputAttributes[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `prop:${K}`]?: UiInput[K] } & OneOf<"inputId", UiInput["inputId"]>;
        "ui-panel-modal": Omit<UiPanelModal, keyof UiPanelModalAttributes> & { [K in keyof UiPanelModal & keyof UiPanelModalAttributes]?: UiPanelModal[K] } & { [K in keyof UiPanelModal & keyof UiPanelModalAttributes as `attr:${K}`]?: UiPanelModalAttributes[K] } & { [K in keyof UiPanelModal & keyof UiPanelModalAttributes as `prop:${K}`]?: UiPanelModal[K] };
        "ui-select": Omit<UiSelect, keyof UiSelectAttributes> & { [K in keyof UiSelect & keyof UiSelectAttributes]?: UiSelect[K] } & { [K in keyof UiSelect & keyof UiSelectAttributes as `attr:${K}`]?: UiSelectAttributes[K] } & { [K in keyof UiSelect & keyof UiSelectAttributes as `prop:${K}`]?: UiSelect[K] };
        "ui-table": UiTable;
        "ui-tag": Omit<UiTag, keyof UiTagAttributes> & { [K in keyof UiTag & keyof UiTagAttributes]?: UiTag[K] } & { [K in keyof UiTag & keyof UiTagAttributes as `attr:${K}`]?: UiTagAttributes[K] } & { [K in keyof UiTag & keyof UiTagAttributes as `prop:${K}`]?: UiTag[K] };
        "ui-test": Omit<UiTest, keyof UiTestAttributes> & { [K in keyof UiTest & keyof UiTestAttributes]?: UiTest[K] } & { [K in keyof UiTest & keyof UiTestAttributes as `attr:${K}`]?: UiTestAttributes[K] } & { [K in keyof UiTest & keyof UiTestAttributes as `prop:${K}`]?: UiTest[K] } & OneOf<"text", UiTest["text"]> & OneOf<"textb", UiTest["textb"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-badge": LocalJSX.IntrinsicElements["ui-badge"] & JSXBase.HTMLAttributes<HTMLUiBadgeElement>;
            "ui-button": LocalJSX.IntrinsicElements["ui-button"] & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-card": LocalJSX.IntrinsicElements["ui-card"] & JSXBase.HTMLAttributes<HTMLUiCardElement>;
            "ui-input": LocalJSX.IntrinsicElements["ui-input"] & JSXBase.HTMLAttributes<HTMLUiInputElement>;
            "ui-panel-modal": LocalJSX.IntrinsicElements["ui-panel-modal"] & JSXBase.HTMLAttributes<HTMLUiPanelModalElement>;
            "ui-select": LocalJSX.IntrinsicElements["ui-select"] & JSXBase.HTMLAttributes<HTMLUiSelectElement>;
            "ui-table": LocalJSX.IntrinsicElements["ui-table"] & JSXBase.HTMLAttributes<HTMLUiTableElement>;
            "ui-tag": LocalJSX.IntrinsicElements["ui-tag"] & JSXBase.HTMLAttributes<HTMLUiTagElement>;
            "ui-test": LocalJSX.IntrinsicElements["ui-test"] & JSXBase.HTMLAttributes<HTMLUiTestElement>;
        }
    }
}
